name: Context with env

run-name: ${{github.event_name}}

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      Var: "job1"
    steps: 
      - run: echo "triggered by ${{github.event_name}}"
      - run: echo "trigger from ref - ${{github.ref}}"
      - run: echo "wf triggered by user - ${{github.actor}}"
      - run: echo "runner is - ${{github.run_id}}"
      - run: echo "runner number is - ${{github.run_number}}"
      - run: echo "value of Var is - ${{env.Var}}" //it will prefer local value always
