name: Context practice

run-name: ${{github.event_name}}

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "triggered by ${{github.event_name}}"
      - run: echo "trigger from ref - ${{github.ref}}"
