name: Env variables access

on:
  push: 
    branches: 
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      Var1: ${{ vars.TEST_ENV }}
    steps:
      - run: echo "running in env $Var1"
