name: On Push Workflow

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run : echo "display the workflow"
